INFO - 2024-09-30 20:53:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 20:58:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:00:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:03:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:03:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:03:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:04:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:07:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-30 21:07:16 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "recuperar_contrasena.php"
[Method: GET, Route: recuperar_contrasena]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('recuperar_contrasena.php')
 2 SYSTEMPATH\Common.php(1169): CodeIgniter\View\View->render('recuperar_contrasena', [], true)
 3 APPPATH\Controllers\Auth.php(110): view('recuperar_contrasena')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->recuperar_contrasena()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:07:53 --> ErrorException: Undefined array key "id"
[Method: POST, Route: enviar_recuperacion]
in APPPATH\Controllers\Auth.php on line 125.
 1 APPPATH\Controllers\Auth.php(125): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\juanxiomaram2024\\timbre25\\app\\Controllers\\Auth.php', 125)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:09:22 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:09:26 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:09:32 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:09:52 --> ErrorException: Undefined array key "id"
[Method: POST, Route: enviar_recuperacion]
in APPPATH\Controllers\Auth.php on line 125.
 1 APPPATH\Controllers\Auth.php(125): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\juanxiomaram2024\\timbre25\\app\\Controllers\\Auth.php', 125)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:10:07 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:13:32 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:13:37 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:15:38 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-09-30 21:15:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:15:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-30 21:15:45 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-09-30 21:15:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:16:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:16:04 --> Intento fallido
INFO - 2024-09-30 21:16:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-30 21:16:14 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(125): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-09-30 21:17:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:17:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:41:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:41:52 --> Intento fallido
INFO - 2024-09-30 21:41:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:42:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:42:07 --> Intento fallido
INFO - 2024-09-30 21:42:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:42:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:43:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:43:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:43:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:45:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:45:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-30 21:45:39 --> ErrorException: Undefined array key "id"
[Method: POST, Route: enviar_recuperacion]
in APPPATH\Controllers\Auth.php on line 121.
 1 APPPATH\Controllers\Auth.php(121): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\juanxiomaram2024\\timbre25\\app\\Controllers\\Auth.php', 121)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:46:50 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(121): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-09-30 21:46:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:46:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-30 21:46:55 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(121): CodeIgniter\Model->update('19', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-09-30 21:48:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:48:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-30 21:48:06 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Auth.php(122): CodeIgniter\Model->update('20', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-30 21:48:39 --> mysqli_sql_exception: Unknown column 'token' in 'field list' in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\BaseModel.php(1028): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Model.php(865): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(122): CodeIgniter\Model->update('20', Array)
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-09-30 21:48:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'token' in 'field list'
[Method: POST, Route: enviar_recuperacion]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `token` = :token:
WHERE `usuarios`.`idusuario` IN :usuarios.idusuario:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Auth.php(122): CodeIgniter\Model->update('20', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:48:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'token' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `token` = \'2c4bfaa7a9e1c002eec718091b62bee59af12292977f93d09449093bffc4fb63f60abedd641696e69917c7979fe2a079b4c0\'
WHERE `usuarios`.`idusuario` IN (\'20\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `token` = \'2c4bfaa7a9e1c002eec718091b62bee59af12292977f93d09449093bffc4fb63f60abedd641696e69917c7979fe2a079b4c0\'
WHERE `usuarios`.`idusuario` IN (\'20\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `token` = :token:
WHERE `usuarios`.`idusuario` IN :usuarios.idusuario:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Auth.php(122): CodeIgniter\Model->update('20', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-09-30 21:48:39 --> [Caused by] mysqli_sql_exception: Unknown column 'token' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `usuarios` SET `token` = \'2c4bfaa7a9e1c002eec718091b62bee59af12292977f93d09449093bffc4fb63f60abedd641696e69917c7979fe2a079b4c0\'
WHERE `usuarios`.`idusuario` IN (\'20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `token` = \'2c4bfaa7a9e1c002eec718091b62bee59af12292977f93d09449093bffc4fb63f60abedd641696e69917c7979fe2a079b4c0\'
WHERE `usuarios`.`idusuario` IN (\'20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `token` = \'2c4bfaa7a9e1c002eec718091b62bee59af12292977f93d09449093bffc4fb63f60abedd641696e69917c7979fe2a079b4c0\'
WHERE `usuarios`.`idusuario` IN (\'20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `token` = :token:
WHERE `usuarios`.`idusuario` IN :usuarios.idusuario:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1028): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Auth.php(122): CodeIgniter\Model->update('20', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-09-30 21:49:28 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php:1762
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1762)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1762): mail('juanmarquez@alu...', '=?UTF-8?Q?Recup...', 'This is a multi...', 'Date: Mon, 30 S...', '-f noreply@tu-d...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(149): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(124): App\Controllers\Auth->sendRecoveryEmail('juanmarquez@alu...', '36ffa7c0466f6f4...')
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2024-09-30 21:49:28 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2024-09-30 21:49:28 --> 
ERROR - 2024-09-30 21:49:28 --> Error al enviar el correo de recuperación: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 30 Sep 2024 21:49:26 +0000
From: =?UTF-8?Q?Soporte=20de=20Timbre=20Autom=C3=A1tico?= &lt;noreply@tu-dominio.com&gt;
Return-Path: &lt;noreply@tu-dominio.com&gt;
Reply-To: &lt;noreply@tu-dominio.com&gt;
User-Agent: CodeIgniter
X-Sender: noreply@tu-dominio.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66fb1ce6afa027.70180760@tu-dominio.com&gt;
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=&quot;B_ALT_66fb1ce6afa102.70903467&quot;
</pre>
INFO - 2024-09-30 21:49:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:49:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:49:53 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php:1762
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1762)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1762): mail('xiomaramondino@...', '=?UTF-8?Q?Recup...', 'This is a multi...', 'Date: Mon, 30 S...', '-f noreply@tu-d...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(149): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(124): App\Controllers\Auth->sendRecoveryEmail('xiomaramondino@...', 'ad19fced49d6086...')
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2024-09-30 21:49:53 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2024-09-30 21:49:53 --> 
ERROR - 2024-09-30 21:49:53 --> Error al enviar el correo de recuperación: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 30 Sep 2024 21:49:50 +0000
From: =?UTF-8?Q?Soporte=20de=20Timbre=20Autom=C3=A1tico?= &lt;noreply@tu-dominio.com&gt;
Return-Path: &lt;noreply@tu-dominio.com&gt;
Reply-To: &lt;noreply@tu-dominio.com&gt;
User-Agent: CodeIgniter
X-Sender: noreply@tu-dominio.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66fb1cfeee7322.21257008@tu-dominio.com&gt;
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=&quot;B_ALT_66fb1cfeee7412.29332618&quot;
</pre>
INFO - 2024-09-30 21:49:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:49:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:50:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:50:26 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php:1762
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1762)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1762): mail('xiomaramondino@...', '=?UTF-8?Q?Recup...', 'This is a multi...', 'Date: Mon, 30 S...', '-f noreply@tu-d...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(149): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(124): App\Controllers\Auth->sendRecoveryEmail('xiomaramondino@...', 'f99c7820e565256...')
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2024-09-30 21:50:26 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2024-09-30 21:50:26 --> 
ERROR - 2024-09-30 21:50:26 --> Error al enviar el correo de recuperación: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 30 Sep 2024 21:50:24 +0000
From: =?UTF-8?Q?Soporte=20de=20Timbre=20Autom=C3=A1tico?= &lt;noreply@tu-dominio.com&gt;
Return-Path: &lt;noreply@tu-dominio.com&gt;
Reply-To: &lt;noreply@tu-dominio.com&gt;
User-Agent: CodeIgniter
X-Sender: noreply@tu-dominio.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66fb1d207dba98.04523832@tu-dominio.com&gt;
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=&quot;B_ALT_66fb1d207dbb43.62300282&quot;
</pre>
INFO - 2024-09-30 21:50:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:50:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:51:17 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php:1762
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1762)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1762): mail('xiomaramondino@...', '=?UTF-8?Q?Recup...', 'This is a multi...', 'Date: Mon, 30 S...', '-f noreply@tu-d...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(149): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(124): App\Controllers\Auth->sendRecoveryEmail('xiomaramondino@...', 'a118bf3961fbd7a...')
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2024-09-30 21:51:17 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2024-09-30 21:51:17 --> 
ERROR - 2024-09-30 21:51:17 --> Error al enviar el correo de recuperación: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 30 Sep 2024 21:51:15 +0000
From: =?UTF-8?Q?Soporte=20de=20Timbre=20Autom=C3=A1tico?= &lt;noreply@tu-dominio.com&gt;
Return-Path: &lt;noreply@tu-dominio.com&gt;
Reply-To: &lt;noreply@tu-dominio.com&gt;
User-Agent: CodeIgniter
X-Sender: noreply@tu-dominio.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66fb1d53c87fd3.72160330@tu-dominio.com&gt;
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=&quot;B_ALT_66fb1d53c88081.99095400&quot;
</pre>
INFO - 2024-09-30 21:51:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:51:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:53:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 21:53:07 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php:1762
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1762)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1762): mail('xiomaramondino@...', '=?UTF-8?Q?Recup...', 'This is a multi...', 'Date: Mon, 30 S...', '-f noreply@tu-d...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(149): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(124): App\Controllers\Auth->sendRecoveryEmail('xiomaramondino@...', '31545fe0d56802f...')
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2024-09-30 21:53:07 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2024-09-30 21:53:07 --> 
ERROR - 2024-09-30 21:53:07 --> Error al enviar el correo de recuperación: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 30 Sep 2024 21:53:05 +0000
From: =?UTF-8?Q?Soporte=20de=20Timbre=20Autom=C3=A1tico?= &lt;noreply@tu-dominio.com&gt;
Return-Path: &lt;noreply@tu-dominio.com&gt;
Reply-To: &lt;noreply@tu-dominio.com&gt;
User-Agent: CodeIgniter
X-Sender: noreply@tu-dominio.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66fb1dc19ac448.62595738@tu-dominio.com&gt;
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=&quot;B_ALT_66fb1dc19ac517.37584001&quot;
</pre>
INFO - 2024-09-30 21:53:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 21:53:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-30 22:10:53 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php:1762
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1762)
#1 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1762): mail('xiomaramondino@...', '=?UTF-8?Q?Recup...', 'This is a multi...', 'Date: Mon, 30 S...', '-f noreply@tu-d...')
#2 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1694): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Email\Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(149): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\juanxiomaram2024\timbre25\app\Controllers\Auth.php(124): App\Controllers\Auth->sendRecoveryEmail('xiomaramondino@...', '4a600da23f3a3f3...')
#6 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(933): App\Controllers\Auth->enviar_recuperacion()
#7 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\juanxiomaram2024\timbre25\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\juanxiomaram2024\timbre25\public\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2024-09-30 22:10:53 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2024-09-30 22:10:53 --> 
ERROR - 2024-09-30 22:10:53 --> Error al enviar el correo de recuperación: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 30 Sep 2024 22:10:51 +0000
From: =?UTF-8?Q?Soporte=20de=20Timbre=20Autom=C3=A1tico?= &lt;noreply@tu-dominio.com&gt;
Return-Path: &lt;noreply@tu-dominio.com&gt;
Reply-To: &lt;noreply@tu-dominio.com&gt;
User-Agent: CodeIgniter
X-Sender: noreply@tu-dominio.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66fb21eb4f5b90.41015414@tu-dominio.com&gt;
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=&quot;B_ALT_66fb21eb4f5c70.95816456&quot;
</pre>
INFO - 2024-09-30 22:10:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-30 22:10:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
